import pandas as pd

file = pd.ExcelFile('NASCRankings.xlsx') # Source file from NASPA.

seed = pd.read_excel(file, 'seed')
round1 = pd.read_excel(file, 'Round 1')
round2 = pd.read_excel(file, 'Round 2')
round3 = pd.read_excel(file, 'Round 3')
round4 = pd.read_excel(file, 'Round 4')
round5 = pd.read_excel(file, 'Round 5')
round6 = pd.read_excel(file, 'Round 6')
round7 = pd.read_excel(file, 'Round 7')
round8 = pd.read_excel(file, 'Round 8')
round9 = pd.read_excel(file, 'Round 9')
round10 = pd.read_excel(file, 'Round 10')
round11 = pd.read_excel(file, 'Round 11')
round12 = pd.read_excel(file, 'Round 12')
round13 = pd.read_excel(file, 'Round 13')
round14 = pd.read_excel(file, 'Round 14')
round15 = pd.read_excel(file, 'Round 15')
round16 = pd.read_excel(file, 'Round 16')
round17 = pd.read_excel(file, 'Round 17')
round18 = pd.read_excel(file, 'Round 18')
round19 = pd.read_excel(file, 'Round 19')
round20 = pd.read_excel(file, 'Round 20')
round21 = pd.read_excel(file, 'Round 21')
round22 = pd.read_excel(file, 'Round 22')
round23 = pd.read_excel(file, 'Round 23')
round24 = pd.read_excel(file, 'Round 24')
round25 = pd.read_excel(file, 'Round 25')
round26 = pd.read_excel(file, 'Round 26')
round27 = pd.read_excel(file, 'Round 27')
round28 = pd.read_excel(file, 'Round 28')
round29 = pd.read_excel(file, 'Round 29')
round30 = pd.read_excel(file, 'Round 30')
round31 = pd.read_excel(file, 'Round 31')




merge_1 = pd.merge(seed, round1, on="name")
merge_2 = pd.merge(merge_1, round2, on="name")
merge_3 = pd.merge(merge_2, round3, on="name")
merge_4 = pd.merge(merge_3, round4, on="name")
merge_5 = pd.merge(merge_4, round5, on="name")
merge_6 = pd.merge(merge_5, round6, on="name")
merge_7 = pd.merge(merge_6, round7, on="name")
merge_8 = pd.merge(merge_7, round8, on="name")
merge_9 = pd.merge(merge_8, round9, on="name")
merge_10 = pd.merge(merge_9, round10, on="name")
merge_11 = pd.merge(merge_10, round11, on="name")
merge_12 = pd.merge(merge_11, round12, on="name")
merge_13 = pd.merge(merge_12, round13, on="name")
merge_14 = pd.merge(merge_13, round14, on="name")
merge_15 = pd.merge(merge_14, round15, on="name")
merge_16 = pd.merge(merge_15, round16, on="name")
merge_17 = pd.merge(merge_16, round17, on="name")
merge_18 = pd.merge(merge_17, round18, on="name")
merge_19 = pd.merge(merge_18, round19, on="name")
merge_20 = pd.merge(merge_19, round20, on="name")
merge_21 = pd.merge(merge_20, round21, on="name")
merge_22 = pd.merge(merge_21, round22, on="name")
merge_23 = pd.merge(merge_22, round23, on="name")
merge_24 = pd.merge(merge_23, round24, on="name")
merge_25 = pd.merge(merge_24, round25, on="name")
merge_26 = pd.merge(merge_25, round26, on="name")
merge_27 = pd.merge(merge_26, round27, on="name")
merge_28 = pd.merge(merge_27, round28, on="name")
merge_29 = pd.merge(merge_28, round29, on="name")
merge_30 = pd.merge(merge_29, round30, on="name")
merge_31 = pd.merge(merge_30, round31, on="name")
merge_31.columns.values[1] = 'seed'
for i in range(1,32):
    merge_31.columns.values[i+1] = 'Round ' + str(i)

merge_31.to_csv('allrounds.csv')
